name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  google_sign_in: ^6.2.1
  web: ^0.5.1
  
  # NUOVE DIPENDENZE
  provider: ^6.1.2 # Per la gestione dello stato
  flutter_secure_storage: ^9.0.0 # Per memorizzare il token JWT in modo sicuro

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google-logo.png